# /********************************************************************************
# * Copyright (c) 2022 Contributors to the Eclipse Foundation
# *
# * See the NOTICE file(s) distributed with this work for additional
# * information regarding copyright ownership.
# *
# * This program and the accompanying materials are made available under the
# * terms of the Apache License 2.0 which is available at
# * http://www.apache.org/licenses/LICENSE-2.0
# *
# * SPDX-License-Identifier: Apache-2.0
# ********************************************************************************/

name: Build kuksa-databroker

on:
  push:
    branches: [ master ]
  pull_request:
  workflow_call:
  workflow_dispatch:

concurrency:
      group: ${{ github.ref }}-${{ github.workflow }}
      cancel-in-progress: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: databroker-lint-${{ hashFiles('**/Cargo.lock') }}
      - name: Show toolchain information
        working-directory: ${{github.workspace}}
        run: |
          rustup toolchain list
          cargo --version
      - name: cargo fmt
        working-directory: ${{github.workspace}}
        run: cargo fmt -- --check
      - name: cargo clippy
        working-directory: ${{github.workspace}}
        run: cargo clippy --all-targets -- -W warnings -D warnings
      - name: cargo clippy (feature viss)
        working-directory: ${{github.workspace}}
        run: cargo clippy --features viss --all-targets -- -W warnings -D warnings

  test:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: databroker-test-${{ hashFiles('**/Cargo.lock') }}
      - name: Show toolchain information
        working-directory: ${{github.workspace}}
        run: |
          rustup toolchain list
          cargo --version
      - name: Install cargo tarpaulin (unless already installed)
        run: |
          which cargo-tarpaulin || cargo install cargo-tarpaulin
      - name: Run tests and report code coverage
        run: |
          cargo tarpaulin -o xml \
            --exclude-files databroker/tests/* \
            --exclude-files databroker/tests/world/*

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: Code coverage report
          path: cobertura.xml

      # - name: Publish coverage report as comment
      #   uses: 5monkeys/cobertura-action@v12
      #   if: github.event_name == 'pull_request'
      #   with:
      #     path: cobertura.xml
      #     repo_token: ${{ secrets.GITHUB_TOKEN }}
      #     minimum_coverage: 40

  check_ghcr_push:
    name: Check access rights
    uses: eclipse-kuksa/kuksa-actions/.github/workflows/check_ghcr_push.yml@2
    secrets: inherit

  build-container:
    name: Build multiarch container
    runs-on: ubuntu-latest

    needs: check_ghcr_push

    steps:
    - uses: actions/checkout@v4
    - uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: databroker-release-${{ hashFiles('**/Cargo.lock') }}
    - name: Install build prerequisites
      working-directory: ${{github.workspace}}/
      run: |
        which cargo-license || cargo install cargo-license
        which cross || cargo install cross
    - name: Build
      working-directory: ${{github.workspace}}/
      run: |
        ./build-all-targets.sh
    - name: Set container metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        # list of Docker images to use as base name for tags
        images: |
          ghcr.io/eclipse-kuksa/kuksa-databrokerdatabroker
        # generate Docker tags based on the following events/attributes
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Setup Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to the Container registry
      if: needs.check_ghcr_push.outputs.push == 'true'
      uses: docker/login-action@v3
      with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build kuksa-databroker container and push to ghcr.io (and ttl.sh)
      id: ghcr-build
      if: needs.check_ghcr_push.outputs.push == 'true'
      uses: docker/build-push-action@v5
      with:
        platforms: |
          linux/amd64
          linux/arm64
          linux/riscv64
        file: ./Dockerfile
        context: .
        push: true
        tags: |
          ${{ steps.meta.outputs.tags }}
          ttl.sh/eclipse-kuksa/kuksa-databroker-${{github.sha}}
        labels: ${{ steps.meta.outputs.labels }}
        # Provenance to solve that an unknown/unkown image is shown on ghcr.io
        # Same problem as described in https://github.com/orgs/community/discussions/45969
        provenance: false

    - name: Build ephemeral kuksa-databroker container and push to ttl.sh
      if: needs.check_ghcr_push.outputs.push == 'false'
      id: tmp-build
      uses: docker/build-push-action@v5
      with:
        platforms: |
          linux/amd64
          linux/arm64
          linux/riscv64
        file: ./Dockerfile
        context: .
        push: true
        tags: "ttl.sh/eclipse-kuksa/kuksa-databroker-${{github.sha}}"
        labels: ${{ steps.meta.outputs.labels }}
        # Provenance to solve that an unknown/unkown image is shown on ghcr.io
        # Same problem as described in https://github.com/orgs/community/discussions/45969
        provenance: false

    - name: Posting message
      uses: ./.github/actions/post-container-location
      with:
        image: ttl.sh/eclipse-kuksa/kuksa-databroker-${{github.sha}}

    - name: "Archiving AMD64 artifacts"
      uses: actions/upload-artifact@v4
      with:
          name: databroker-amd64
          path: ${{github.workspace}}/dist/amd64

    - name: "Archiving ARM64 artifacts"
      uses: actions/upload-artifact@v4
      with:
          name: databroker-arm64
          path: ${{github.workspace}}/dist/arm64

    - name: "Archiving RISCV64 artifacts"
      uses: actions/upload-artifact@v4
      with:
        name: databroker-riscv64
        path: ${{github.workspace}}/dist/riscv64


  integration-test:
    name: Run integration test
    runs-on: ubuntu-latest
    needs: [build-container]

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - uses: actions/checkout@v4

      - name: Run integration test on AMD64 container
        env:
          DATABROKER_IMAGE: ttl.sh/eclipse-kuksa/kuksa-databroker-${{github.sha}}
          CONTAINER_PLATFORM: linux/amd64
        run: |
          ${{github.workspace}}/integration_test/run.sh

      - name: Run integration test on ARM64 container
        env:
          DATABROKER_IMAGE: ttl.sh/eclipse-kuksa/kuksa-databroker-${{github.sha}}
          CONTAINER_PLATFORM: linux/arm64
        run: |
          ${{github.workspace}}/integration_test/run.sh

      - name: Run integration test on RISCV64 container
        env:
          DATABROKER_IMAGE: ttl.sh/eclipse-kuksa/kuksa-databroker-${{github.sha}}
          CONTAINER_PLATFORM: linux/riscv64
        run: |
          ${{github.workspace}}/integration_test/run.sh

  bom:
    name: Check Bill of Material
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: databroker-bom-${{ hashFiles('**/Cargo.lock') }}

      - name: "License check and Dash output generation"
        working-directory: ${{github.workspace}}/createbom
        run: |
         which cargo-license || cargo install cargo-license
         python3 createbom.py --dash ${{github.workspace}}/dash-databroker-deps ../databroker

      - name: Dash license check
        uses: eclipse-kuksa/kuksa-actions/check-dash@2
        with:
          dashinput: ${{github.workspace}}/dash-databroker-deps
